version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pongapp
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  # server:
  #   build: 
  #     context: ./Server
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   volumes:
  #     - type: bind
  #       source: .
  #       target: /app
  #   ports: 
  #     - "3000:3000"
volumes:
  db:
    driver: local